### ISSUE TITLE
Build errors with gcc 8.1.1

### ISSUE THREAD

**Issue by DennisMitchell** [egel-lang/egel#1]
Egel fails to build with gcc 8.1.1. This appears to be due to new warnings introduced in gcc 8, which the build script treats as errors.

Running **build.sh** produces the following output.

```
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 utils.cpp -o utils.o
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 lexical.cpp -o lexical.o
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 operators.cpp -o operators.o
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 syntactical.cpp -o syntactical.o
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 ast.cpp -o ast.o
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 transform.cpp -o transform.o
c++ --std=c++17 -Werror -c -Wall -pedantic -fPIC -O3 semantical.cpp -o semantical.o
semantical.cpp: In member function ‘virtual void VisitDeclare::visit_expr_combinator(const Position&, const UnicodeStrings&, const icu_60::UnicodeString&)’:
semantical.cpp:76:38: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
             } catch (ErrorSemantical e) {
                                      ^
semantical.cpp:86:38: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
             } catch (ErrorSemantical e) {
                                      ^
semantical.cpp: In member function ‘void RewriteIdentify::declare(const Position&, const icu_60::UnicodeString&, const icu_60::UnicodeString&)’:
semantical.cpp:172:34: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
         } catch (ErrorSemantical e) {
                                  ^
cc1plus: all warnings being treated as errors
gmake: *** [Makefile:69: semantical.o] Error 1
c++ --std=c++17 -Werror -c -Wall -pedantic -O3 -fPIC semantical.cpp -o semantical.o
semantical.cpp: In member function ‘virtual void VisitDeclare::visit_expr_combinator(const Position&, const UnicodeStrings&, const icu_60::UnicodeString&)’:
semantical.cpp:76:38: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
             } catch (ErrorSemantical e) {
                                      ^
semantical.cpp:86:38: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
             } catch (ErrorSemantical e) {
                                      ^
semantical.cpp: In member function ‘void RewriteIdentify::declare(const Position&, const icu_60::UnicodeString&, const icu_60::UnicodeString&)’:
semantical.cpp:172:34: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
         } catch (ErrorSemantical e) {
                                  ^
cc1plus: all warnings being treated as errors
gmake: *** [Makefile:69: semantical.o] Error 1
c++ --std=c++17 -Werror -c -Wall -pedantic -O3 semantical.cpp -o semantical.o
semantical.cpp: In member function ‘virtual void VisitDeclare::visit_expr_combinator(const Position&, const UnicodeStrings&, const icu_60::UnicodeString&)’:
semantical.cpp:76:38: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
             } catch (ErrorSemantical e) {
                                      ^
semantical.cpp:86:38: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
             } catch (ErrorSemantical e) {
                                      ^
semantical.cpp: In member function ‘void RewriteIdentify::declare(const Position&, const icu_60::UnicodeString&, const icu_60::UnicodeString&)’:
semantical.cpp:172:34: error: catching polymorphic type ‘class ErrorSemantical’ by value [-Werror=catch-value=]
         } catch (ErrorSemantical e) {
                                  ^
cc1plus: all warnings being treated as errors
gmake: *** [Makefile:69: semantical.o] Error 1
c++ --std=c++17 -Werror -fPIC -c -Wall -pedantic -O3 io.cpp -o io.o
io.cpp: In member function ‘virtual VMObjectPtr Readline::apply(const VMObjectPtr&) const’:
io.cpp:410:37: error: catching polymorphic type ‘class std::exception’ by value [-Werror=catch-value=]
             } catch (std::exception e) {
                                     ^
cc1plus: all warnings being treated as errors
gmake: *** [Makefile:34: io.o] Error 1
c++ --std=c++17 -Werror -fPIC -c -Wall -pedantic -O3 random.cpp -o random.o
c++ --std=c++17 -Werror -shared -licuio -licui18n -licuuc -licudata  random.o -o ../random.ego
c++ --std=c++17 -Werror -fPIC -c -Wall -pedantic -O3 regex.cpp -o regex.o
c++ --std=c++17 -Werror -shared -licuio -licui18n -licuuc -licudata  regex.o -o ../regex.ego
c++ --std=c++17 -Werror -fPIC -c -Wall -pedantic -O3 fs.cpp -o fs.o
c++ --std=c++17 -Werror -shared -licuio -licui18n -licuuc -licudata  fs.o -lstdc++fs -o ../fs.ego
```
